export const BASE_URL = "http://localhost:5000";


export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini (fmr. Swaziland)",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (formerly Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const PACKAGES = [
  {
    id: "standard",
    title: "Standard Plan",
    price: 1,
    coin: 100,
  },
  {
    id: "pro",
    title: "Pro Plan",
    price: 5,
    coin: 500,
  },
  {
    id: "exclusive",
    title: "Exclusive Plan",
    price: 10,
    coin: 1000,
  },
  {
    recipeName: "",
    recipeImage: "",
    recipeDetails: "",
    youtubeVideoCode: "",
    country: "",
    category: "",
    creatorEmail: "",
    watchCount: 0,
    purchasedBy: [],
  },

  [
    {
      recipeName: "Spaghetti Carbonara",
      recipeImage: "https://i.ibb.co/LSFzGhm/Screenshot-1.png",
      recipeDetails:
        "Spaghetti Carbonara is a classic Italian pasta dish made with eggs, cheese, bacon, and black pepper. It's creamy, rich, and incredibly delicious.",
      youtubeVideoCode: "v4aXJsfl_Ss?si=gU8EEij6R7Stvdx0",
      country: "Italy",
      category: "Pasta",
      creatorEmail: "chef@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Margherita Pizza",
      recipeImage: "https://i.ibb.co/b6V6BBJ/Screenshot-2.png",
      recipeDetails:
        "Margherita Pizza is a traditional Italian pizza topped with tomato sauce, fresh mozzarella cheese, basil, and olive oil. It's simple yet incredibly flavorful.",
      youtubeVideoCode: "vcfNpDtVqOw?si=tIQVFbXYmcTukSQH",
      country: "Italy",
      category: "Pizza",
      creatorEmail: "pizzamaker@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Chicken Alfredo Pasta",
      recipeImage: "https://i.ibb.co/FBgRGsm/Screenshot-3.png",
      recipeDetails:
        "Chicken Alfredo Pasta is a creamy Italian pasta dish made with fettuccine pasta, chicken breast, heavy cream, butter, and Parmesan cheese. It's rich, indulgent, and satisfying.",
      youtubeVideoCode: "6eAfeodmXW0?si=7I88R4UhIKUeB2g2",
      country: "Italy",
      category: "Pasta",
      creatorEmail: "chef@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Greek Salad",
      recipeImage: "https://i.ibb.co/zQ1j2hL/Screenshot-4.png",
      recipeDetails:
        "Greek Salad is a refreshing salad made with tomatoes, cucumbers, onions, olives, feta cheese, and a simple vinaigrette dressing. It's light, healthy, and perfect for summer.",
      youtubeVideoCode: "tD-N9x2mAes?si=bc0e65b207e3478e",
      country: "Greece",
      category: "Salad",
      creatorEmail: "chef@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Tomato Soup",
      recipeImage: "https://i.ibb.co/3s1spcC/Screenshot-5.png",
      recipeDetails:
        "Tomato Soup is a classic comfort food made with ripe tomatoes, onions, garlic, and herbs. It's warm, hearty, and perfect for chilly days.",
      youtubeVideoCode: "ICSVpfAVERI?si=X7zw6SB-7ZJUf8I-",
      country: "International",
      category: "Soup",
      creatorEmail: "chef@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Apple Pie",
      recipeImage: "https://i.ibb.co/d41TWvv/Screenshot-10.png",
      recipeDetails:
        "Apple Pie is a classic American dessert made with tender, flaky pie crust and a sweet apple filling. It's comforting, nostalgic, and perfect for any occasion.",
      youtubeVideoCode: "ICSVpfAVERI?si=X7zw6SB-7ZJUf8I-",
      country: "United States",
      category: "Pie",
      creatorEmail: "baker@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "BLT Sandwich",
      recipeImage: "https://i.ibb.co/kGZ8j4Q/Screenshot-9.png",
      recipeDetails:
        "BLT Sandwich is a classic American sandwich made with crispy bacon, fresh lettuce, ripe tomatoes, and mayonnaise on toasted bread. It's simple yet incredibly delicious.",
      youtubeVideoCode: "cxlkfs9284?si=2f7f3856b47149cd",
      country: "United States",
      category: "Sandwich",
      creatorEmail: "chef@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Chicken Caesar Salad",
      recipeImage: "https://i.ibb.co/WfPH9CZ/Screenshot-8.png",
      recipeDetails:
        "Chicken Caesar Salad is a classic salad made with romaine lettuce, grilled chicken breast, croutons, Parmesan cheese, and Caesar dressing. It's hearty, flavorful, and satisfying.",
      youtubeVideoCode: "tD-N9x2mAes?si=bc0e65b207e3478e",
      country: "International",
      category: "Salad",
      creatorEmail: "chef@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Lasagna",
      recipeImage: "https://i.ibb.co/0Z50XSN/Screenshot-7.png",
      recipeDetails:
        "Lasagna is a classic Italian pasta dish made with layers of lasagna noodles, marinara sauce, ricotta cheese, mozzarella cheese, and ground beef. It's rich, hearty, and incredibly flavorful.",
      youtubeVideoCode: "v4aXJsfl_Ss?si=gU8EEij6R7Stvdx0",
      country: "Italy",
      category: "Main Dish",
      creatorEmail: "chef@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Caesar Salad",
      recipeImage: "https://i.ibb.co/510dPWy/Screenshot-6.png",
      recipeDetails:
        "Caesar Salad is a classic salad made with romaine lettuce, croutons, Parmesan cheese, and Caesar dressing. It's simple, delicious, and perfect for any occasion.",
      youtubeVideoCode: "vcfNpDtVqOw?si=tIQVFbXYmcTukSQH",
      country: "International",
      category: "Salad",
      creatorEmail: "chef@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Vegetable Soup",
      recipeImage: "https://i.ibb.co/1mtXRjP/Screenshot-14.png",
      recipeDetails:
        "Vegetable Soup is a nutritious and comforting soup made with a variety of fresh vegetables, herbs, and broth. It's perfect for warming up on cold days and packed with vitamins and minerals.",
      youtubeVideoCode: "6eAfeodmXW0?si=7I88R4UhIKUeB2g2",
      country: "International",
      category: "Soup",
      creatorEmail: "chef@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Mushroom Risotto",
      recipeImage: "https://i.ibb.co/t21sLJV/Screenshot-13.png",
      recipeDetails:
        "Mushroom Risotto is a creamy Italian rice dish made with Arborio rice, mushrooms, onions, garlic, Parmesan cheese, and white wine. It's indulgent, flavorful, and perfect for special occasions.",
      youtubeVideoCode: "ICSVpfAVERI?si=X7zw6SB-7ZJUf8I-",
      country: "Italy",
      category: "Main Dish",
      creatorEmail: "chef@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Chocolate Cake",
      recipeImage: "https://i.ibb.co/sth8dZt/Screenshot-12.png",
      recipeDetails:
        "Chocolate Cake is a decadent dessert made with rich cocoa powder, butter, sugar, eggs, and flour. It's moist, indulgent, and perfect for chocolate lovers.",
      youtubeVideoCode: "v4aXJsfl_Ss?si=gU8EEij6R7Stvdx0",
      country: "International",
      category: "Dessert",
      creatorEmail: "baker@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Tiramisu",
      recipeImage: "https://i.ibb.co/DLpfCmX/Screenshot-11.png",
      recipeDetails:
        "Tiramisu is a classic Italian dessert made with layers of coffee-soaked ladyfingers, mascarpone cheese, cocoa powder, and liqueur. It's creamy, indulgent, and perfect for special occasions.",
      youtubeVideoCode: "6eAfeodmXW0?si=7I88R4UhIKUeB2g2",
      country: "Italy",
      category: "Dessert",
      creatorEmail: "chef@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Ratatouille",
      recipeImage: "https://i.ibb.co/FBgRGsm/Screenshot-3.png",
      recipeDetails:
        "Ratatouille is a traditional French Provencal stewed vegetable dish made with eggplant, zucchini, bell peppers, onions, tomatoes, and herbs. It's flavorful, hearty, and perfect for vegetarians.",
      youtubeVideoCode: "vcfNpDtVqOw?si=tIQVFbXYmcTukSQH",
      country: "France",
      category: "Main Dish",
      creatorEmail: "chef@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Sushi Rolls",
      recipeImage: "https://i.ibb.co/FBgRGsm/Screenshot-3.png",
      recipeDetails:
        "Sushi Rolls are a popular Japanese dish made with sushi rice, seaweed, and a variety of fillings such as fish, seafood, vegetables, and avocado. They're delicious, healthy, and perfect for sushi lovers.",
      youtubeVideoCode: "ICSVpfAVERI?si=X7zw6SB-7ZJUf8I-",
      country: "Japan",
      category: "Main Dish",
      creatorEmail: "sushichef@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Chicken Tikka Masala",
      recipeImage: "https://i.ibb.co/zQ1j2hL/Screenshot-4.png",
      recipeDetails:
        "Chicken Tikka Masala is a popular Indian curry dish made with marinated and roasted chicken pieces in a spiced tomato-based sauce. It's flavorful, aromatic, and perfect with rice or naan bread.",
      youtubeVideoCode: "v4aXJsfl_Ss?si=gU8EEij6R7Stvdx0",
      country: "India",
      category: "Main Dish",
      creatorEmail: "chef@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
    {
      recipeName: "Hamburger",
      recipeImage: "https://i.ibb.co/3s1spcC/Screenshot-5.png",
      recipeDetails:
        "Hamburger is a classic American sandwich made with a seasoned ground beef patty, lettuce, tomato, onion, pickles, and condiments on a bun. It's simple, satisfying, and perfect for summer BBQs.",
      youtubeVideoCode: "6eAfeodmXW0?si=7I88R4UhIKUeB2g2",
      country: "United States",
      category: "Sandwich",
      creatorEmail: "chef@example.com",
      watchCount: 0,
      purchasedBy: [],
    },
  ],
];